# Generated by Django 5.2 on 2025-05-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
