# Generated by Django 5.2 on 2025-05-24 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_triviavote'),
        ('titles', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='news_news_slug_915ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['published_at'], name='news_news_publish_377f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='trivia',
            index=models.Index(fields=['upvotes'], name='news_trivia_upvotes_9c2ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='trivia',
            index=models.Index(fields=['created_at'], name='news_trivia_created_f79db7_idx'),
        ),
    ]
