# Generated by Django 5.2 on 2025-05-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_source_name_alter_trivia_downvotes_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='news_news_slug_915ecd_idx',
        ),
        migrations.RemoveIndex(
            model_name='news',
            name='news_news_publish_377f0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='trivia',
            name='news_trivia_upvotes_9c2ab4_idx',
        ),
        migrations.RemoveIndex(
            model_name='trivia',
            name='news_trivia_created_f79db7_idx',
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
